name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  GATSBY_EMAILJS_SERVICE_ID: ${{ secrets.GATSBY_EMAILJS_SERVICE_ID }}
  GATSBY_EMAILJS_TEMPLATE_ID: ${{ secrets.GATSBY_EMAILJS_TEMPLATE_ID }}
  GATSBY_EMAILJS_USER_ID: ${{ secrets.GATSBY_EMAILJS_USER_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npx npm@6 ci
          npx npm@6 run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
